
#=================================================================================
# 容器相关设置
server:
  port: 9090
  context-path: /springboot-simple-demo


#=================================================================================
# spring 组件相关设置

spring:
  datasource: 
    url: jdbc:mysql://192.168.10.26:3306/springboot_demodb?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf-8&characterSetResults=UTF-8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: jkgly@163.coM@26


#=================================================================================
# 其他辅助框架相关配置

#=================================================================================
# 自定义参数相关配置

#=================================================================================